/**
 * Builds responsive AVIF/WebP/JPEG derivatives from assets/source into public/images.
 * Run with `npm run images`. Output is committed, so the site build never needs sharp.
 */
import sharp from 'sharp';
import { mkdir, readdir, unlink, writeFile, rm } from 'node:fs/promises';
import path from 'node:path';

const SRC = 'assets/source';
const OUT = 'public/images';

/** @type {{file:string,name:string,widths:number[],crop?:{top:number,height:number}}[]} */
const JOBS = [
  { file: 'hero-dining-room.png', name: 'hero', widths: [640, 960, 1280, 1920, 2560] },
  // The source carries a photographer watermark across the bottom strip; crop it out.
  { file: 'room-interior.webp', name: 'room', widths: [640, 960, 1280], crop: { top: 0, height: 900 } },
  { file: 'counter.webp', name: 'counter', widths: [640, 960, 1280] },
];

await mkdir(OUT, { recursive: true });
// Clear previously generated top-level derivatives. Subdirectories (menu/) are
// handled by their own step, so only unlink files here.
for (const entry of await readdir(OUT, { withFileTypes: true }).catch(() => [])) {
  if (entry.isFile()) await unlink(path.join(OUT, entry.name));
}

for (const job of JOBS) {
  const base = sharp(path.join(SRC, job.file), { failOn: 'error' }).rotate();
  const meta = await base.metadata();
  const pipeline = job.crop
    ? base.extract({ left: 0, top: job.crop.top, width: meta.width, height: Math.min(job.crop.height, meta.height) })
    : base;
  const buf = await pipeline.toBuffer();

  for (const w of job.widths) {
    if (w > meta.width * 1.05) continue;
    const resized = () => sharp(buf).resize({ width: w, withoutEnlargement: true });
    await Promise.all([
      resized().avif({ quality: 55, effort: 6 }).toFile(`${OUT}/${job.name}-${w}.avif`),
      resized().webp({ quality: 74, effort: 5 }).toFile(`${OUT}/${job.name}-${w}.webp`),
      resized().jpeg({ quality: 78, mozjpeg: true, progressive: true }).toFile(`${OUT}/${job.name}-${w}.jpg`),
    ]);
  }

  // 24px LQIP inlined as a blurred placeholder so the hero never flashes empty.
  const lqip = await sharp(buf).resize({ width: 24 }).blur(1.4).webp({ quality: 40 }).toBuffer();
  console.log(`${job.name}: ${job.widths.join('/')} — lqip ${lqip.length}B`);
  console.log(`  data:image/webp;base64,${lqip.toString('base64')}`);
}

// ── Menu item photography ───────────────────────────────────────────────────
// Drop files in assets/source/menu named after the item's slug (spicy-rice.png)
// and re-run. Everything else is automatic: derivatives are generated here and
// src/data/photos.ts is rewritten, so every tile that has a photo starts using
// it and every tile that doesn't keeps the branded placeholder.
const MENU_SRC = path.join(SRC, 'menu');
const MENU_OUT = path.join(OUT, 'menu');
const MENU_WIDTHS = [400, 800, 1200];

await rm(MENU_OUT, { recursive: true, force: true });
await mkdir(MENU_OUT, { recursive: true });

const menuFiles = (await readdir(MENU_SRC).catch(() => []))
  .filter((f) => /\.(png|jpe?g|webp|avif|tiff?)$/i.test(f));

/** @type {Record<string,{widths:number[],lqip:string}>} */
const manifest = {};

for (const file of menuFiles.sort()) {
  const slug = path.basename(file, path.extname(file)).toLowerCase();
  if (!/^[a-z0-9-]+$/.test(slug)) {
    console.warn(`  skipped ${file} — filename must be the item slug, e.g. spicy-rice.png`);
    continue;
  }
  // Square crop: cards show 4:3 and the item page shows 1:1, and a square
  // master covers both under object-cover without a second render.
  const square = await sharp(path.join(MENU_SRC, file), { failOn: 'error' })
    .rotate()
    .resize({ width: 1200, height: 1200, fit: 'cover', position: 'attention' })
    .toBuffer();

  const widths = [];
  for (const w of MENU_WIDTHS) {
    const resized = () => sharp(square).resize({ width: w });
    await Promise.all([
      resized().avif({ quality: 55, effort: 6 }).toFile(`${MENU_OUT}/${slug}-${w}.avif`),
      resized().webp({ quality: 74, effort: 5 }).toFile(`${MENU_OUT}/${slug}-${w}.webp`),
      resized().jpeg({ quality: 78, mozjpeg: true, progressive: true }).toFile(`${MENU_OUT}/${slug}-${w}.jpg`),
    ]);
    widths.push(w);
  }

  const lqip = await sharp(square).resize({ width: 20 }).blur(1.2).webp({ quality: 40 }).toBuffer();
  manifest[slug] = { widths, lqip: `data:image/webp;base64,${lqip.toString('base64')}` };
  console.log(`  menu/${slug}: ${widths.join('/')}`);
}

const entries = Object.entries(manifest)
  .map(([slug, v]) => `  '${slug}': { widths: [${v.widths.join(', ')}], lqip: '${v.lqip}' },`)
  .join('\n');

await writeFile(
  'src/data/photos.ts',
  `/**
 * GENERATED by scripts/optimize-images.mjs — do not edit by hand.
 * Add a photo by dropping <slug>.png into assets/source/menu and running
 * \`npm run images\`. Items missing here fall back to the branded placeholder.
 */
export interface Photo {
  widths: number[];
  /** Inline blurred thumbnail, so a tile never flashes empty. */
  lqip: string;
}

export const PHOTOS: Record<string, Photo> = {
${entries}
};

export const hasPhoto = (slug: string): boolean => slug in PHOTOS;
`,
);
console.log(`menu photos: ${Object.keys(manifest).length} → src/data/photos.ts`);

// Open Graph card: 1200x630, cropped from the hero.
await sharp(path.join(SRC, 'hero-dining-room.png'))
  .resize({ width: 1200, height: 630, fit: 'cover', position: 'attention' })
  .jpeg({ quality: 82, mozjpeg: true })
  .toFile(`${OUT}/og-cover.jpg`);

console.log('og-cover.jpg written');
