/**
 * GENERATED by scripts/optimize-images.mjs — do not edit by hand.
 * Add a photo by dropping <slug>.png into assets/source/menu and running
 * `npm run images`. Items missing here fall back to the branded placeholder.
 */
export interface Photo {
  widths: number[];
  /** Inline blurred thumbnail, so a tile never flashes empty. */
  lqip: string;
}

export const PHOTOS: Record<string, Photo> = {
  'active': { widths: [400, 800, 1200], lqip: 'data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADQAwCdASoUABQAPu1kqk2ppaQiMAgBMB2JQBltBDv3u3p1bkWhVYAA/vN+8uSO3pCzfT7Ik8fq+gCmq+MMBr1KX7phgAAA' },
  'amala': { widths: [400, 800, 1200], lqip: 'data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAACQBACdASoUABQAPulepk2pJSOiN/VYASAdCUAXYAGgqeBolgr/00q4oH3OAAAA/vBApsRG/xKRjYuxSM4t5LGmQMuzlLg1eLrbEpw+HKCng2aYWESKtFF84rWpwTJlaZAbxcVAWrxbtwAA' },
  'assorted': { widths: [400, 800, 1200], lqip: 'data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAABwBQCdASoUABQAPulcqE2pJKQiN/VYASAdCWwAnTKEgsj39GgCtPs1lAUcVHn25R+NCNJAAP7iUju6OA+XzZgQmuUyPix8ggfDvR4Rytsq3tGBJ7ku6GsB39tKFj94Apz3nIlyzTbGMk7J866DEnJ+Wfs9K+3JiWR7tFoUAAA=' },
  'beans-ewa': { widths: [400, 800, 1200], lqip: 'data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAACwBACdASoUABQAPulcp02pJSOiN/VYASAdCWoAuwAPSy7zbEAfR/iR4mKAKLdgAP7x4Fcl4b8D4D2SoUWM2QNcgMHXlDWiHL4SrlOjYbVRG+xZfSzlnmOpFxDv2nSRnfeLeSWkcicAAA==' },
  'beef': { widths: [400, 800, 1200], lqip: 'data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAAAQBQCdASoUABQAPu1krE4ppaSiKA1RMB2JZgCdMzOHQArpWl89Vv2Nln1Lc6e+WcYAAP7wQKvFuqKLA56WBMh8Oc3yJ6VZSqKkyc+WsBqBB3a1vjh+pE6nkML+FiTa7T4We3GuW49vFDVMkWf+6xn/Zn0kEcgBMLrMOncAAAA=' },
  'boiled-egg': { widths: [400, 800, 1200], lqip: 'data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAADwBACdASoUABQAPu1erE2ppSSiMBgMATAdiWwAuwAPS4hMyGx1oNCo3T8GPsJQLGAA/vHgwcHbOy8D6K3mjBY9CMPBwLRwUqyiv060vESZHg13geXKJe65owOeR6AM0zU57C84i8oiIK5V17MZC/0C6VRGAAAA' },
  'bokoto': { widths: [400, 800, 1200], lqip: 'data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAABQBQCdASoUABQAPu1kq06ppaQiKA1RMB2JbACdMoR0l7WAJIJ+V7x9z3rhGlrp79FlUgAA/uJV69L+WmN3xvgsH9uXYtQvDxlKTzFt82rjB9vvNtEos9+ZXep9k9KCBAiXE+RGtnT/rC8SaZqVhuZwvGXX/+seYmVyva/bLBNxNVuatoV73pWJwW3JWijAis34AAAA' },
  'bottled-water': { widths: [400, 800, 1200], lqip: 'data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAACQBACdASoUABQAPu1gqU4ppSOiMBgMATAdiUAYOYGCq2/5DyKLA6G0EPYpuQAA/uqVl0pVNrkGdHl60VU5hslEy9sQkO9yWgqrFpQD+e7/33FbmSJ5zgVa5V28WrH1SKipcAAA' },
  'chicken': { widths: [400, 800, 1200], lqip: 'data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAAAwBQCdASoUABQAPu1srVEppiQiqAqpMB2JaACdMt8BgkwxwZ+pz0uH7BONBwvssO7qJgD6/jHS8yw2qZYljKMhZHWT0vc301vLAFrQHrLhQE9YJ8bS9qvnfBAubDgZXzA10P9TNJBwia9lxbxxzC2nXXcIAA==' },
  'chivita': { widths: [400, 800, 1200], lqip: 'data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwAwCdASoUABQAPu1mq02ppaQiMAgBMB2JQBg9kRhgakNGsxOwJj3AAP7zfvLkj3ZzxeRygyjHZWcYkZ3zDPJmUa2g9dxMWEgeEgZiDgfDTIAA' },
  'coke': { widths: [400, 800, 1200], lqip: 'data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAADwBACdASoUABQAPu1cqk4ppKOiMBgMATAdiWgAsR8cgpgQBAfBfrJgiyqDOanvMAAA/vQy1iO3TsCHhuURi5udo6oCBNLLyhT3icT3V3OP4HiWvkArDyudaDPo0FUklKadG34vDyVgFc5fEnWhsNYAAAA=' },
  'coleslaw': { widths: [400, 800, 1200], lqip: 'data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAABQBQCdASoUABQAPu1cq02ppKQiMBgMATAdiWQAnQAR9prT3yq5Q06n6LJEnRg/YJ9biIAA/u3f7BmgtHwYbMu3SBMJoh0EHoFwagnAHXx88/yrhx7OkCFZV1aU46KEC31IJziHBhhAAA==' },
  'dudu-yoghurt': { widths: [400, 800, 1200], lqip: 'data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADQBACdASoUABQAPtleo02oJaMiN/qoAQAbCWMAygAh4Z+yehqXkcEOdvOUhXKOkAD+5zoZg/1XxQtt8tMdqGWDu846D54VurpdbvljBCgw5898AAA=' },
  'eba': { widths: [400, 800, 1200], lqip: 'data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAADQBACdASoUABQAPu1mqk8ppaOiKA1RMB2JZACxH1XBl842c4Ax7s3Z9r4m8eMKEAD+5zsvXZ8v0CGpyShpIoAgFD6O+cGlEl3sXL46cUeCJ0zZfltVI1V0aBLtNfj1FAARLAAA' },
  'fanta': { widths: [400, 800, 1200], lqip: 'data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAAAQBQCdASoUABQAPu1eqE4ppKOiMBgMATAdiWgAnTKEcAAUycf6qNrdqHrAkX/jc3cAAP7rRtdx9ELjKuUWX9YMzHOJAru84dqMdMtTs+h+GE4dPBo+NZgty8wLr1btfaMDzDK47XkLAJwqUHeAAA==' },
  'fried-rice': { widths: [400, 800, 1200], lqip: 'data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAADQBACdASoUABQAPuFipU2opiOiN/VYARAcCWwArCiqwNIMpkC/hWtBJwATtU4AAAD+84LQYtFPy1SDjIhOtFJnyy9h8D3NQnyefyEMFs2wZH/dS1zhwgbwG+FyyVhSj3KN20q3zqpLJADBR6yPrqZabAAAAA==' },
  'goat-meat': { widths: [400, 800, 1200], lqip: 'data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAACQBACdASoUABQAPu1erE2ppSSiMBgMATAdiUATpmX4D2sCWWXe3jVS/6bMF1AA/vBAq8VT0L3l/Ggg/peUOqeGIaAaaqVSHJHI2JezkB7KROfTyLvYLsAEPAMgz6Uae2dVUiHj0ChdM2X0qDc/zkRgJoegZOzbcgA=' },
  'hollandia': { widths: [400, 800, 1200], lqip: 'data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAwBACdASoUABQAPu1kqk2ppaQiMAgBMB2JYwC/OCHgUcNXPXxqcdcq8gAA/vN9s2DeOiGc8dWnu/pSSTKnetcsEsi/26DKys3mWclCxWi5UAAA' },
  'macbite-bread': { widths: [400, 800, 1200], lqip: 'data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAADQBACdASoUABQAPu1qqk8ppiOpsBgIATAdiWQAnTKEeygVI/mOEeAVTHcl/NLxAAD+6nu4EY1vYEhVpJuYlfLDeUgp7MkYDitOkXODvn6UOn1XKz56xv+3CVQBhtnDcBMJ2k4y/IAAAA==' },
  'maltina': { widths: [400, 800, 1200], lqip: 'data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAADwBACdASoUABQAPu1sqlGppaOiqAqpMB2JaACdL5D5KAJSz0n9eZoPFlVAPsO32AAA/qmZfj9MZoSVxGSNo9ZYsAo/lrghfrM0mmBjdjZfiGPnXUDjV9CbJ+Cn5U6chrcUQg+PqkMrVoDf7jL9iQ3YfBQkHzKqO3PgdTMe3c30QAAA' },
  'moin-moin': { widths: [400, 800, 1200], lqip: 'data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAAAwBQCdASoUABQAPu1oqk+ppiOiKA1RMB2JYgAAKcK22jJQo5aJ2+PAbHGbbNkGKeSOAAD+7YLQJUiBqB4WnjQzuTfDnuckvi5lajp/1KdqUl0m+dhWed+m8xnt+5kNc/85VV/zYmfkTCl6AHBt6EsuPQz3dOuZcRsQ/l84AAAAAA==' },
  'panla': { widths: [400, 800, 1200], lqip: 'data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAAAQBACdASoUABQAPu1qrE8ppiQiMBgIATAdiWUAAC5wqnZrBxALDdF9AAD+8dvJvH50vKWZtojTFqylvplaQBRhHn9MRrDVk+jaIYy8+SccygFs2vwnxuic+weL5p37k7Vx6CJAAAA=' },
  'pepsi': { widths: [400, 800, 1200], lqip: 'data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAABwBACdASoUABQAPu1qrlCppaQiqAqpMB2JQBYj7IA1QvLD/4HUEW/hVUAIAAD+9Cm46VC8vSE4zBiS062HLMC0XDuw7gxRqGTqrfTo0JJ4KJJlT5xpGkl7rWjhk0gA' },
  'plantain-dodo': { widths: [400, 800, 1200], lqip: 'data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAAAwBQCdASoUABQAPulcqE2pJSQiN/VYASAdCWwAnTLTGAAFa4ixpCZe/LSw1KKreT6wAAD+8D87N+hNCEANP5pc+IinYnbLAN98wYwxxkJWfKDRYcWWMohc3ezjU2+v4nOx/EeFg8GQEQvEJKZqudzeZWGJNDCgenulOV9Dk1rnKPVaSgAAAA==' },
  'ponmo': { widths: [400, 800, 1200], lqip: 'data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAABwBQCdASoUABQAPu1wsFKppiSiqAgBMB2JbACdMoR5mKlA7lUD9hCiD18DzlfrBT1AN/wAAP7rivMCPlkjamR8OD1PHkLmlYj7UOUORvNwx4iMn1UX4WDxDFDa1fbN3AZJTV+0HRabvtOiSjEGDnd80RKcZdTuy0IRePGHygJ9dHrAHiO2fqo2GULQn/3QAAA=' },
  'pulpy': { widths: [400, 800, 1200], lqip: 'data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAACQBQCdASoUABQAPu1gq02ppaQiMBgMATAdiWwAnTKEfR+mgCS2+pKOMs16mr4g/KDF73ZzeAD+VHLWb05S2kf77r0coZd2fuSFNWAkXvyapyidzJI0n3zweJkadn0aQmt4Ao0OseB0Xz2ilmmfJ7tYd1RWQhEJFsYAAA==' },
  'rice-and-beans': { widths: [400, 800, 1200], lqip: 'data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAwBACdASoUABQAPtlcpE2oJaOiN/qoAQAbCUAAC4yOHAXLI5eoXfYxmYAA/vTeGbmxNhjd5W8qQkUHnNox3HrJJiUkgcUn21oeM74AAAA=' },
  'schweppes': { widths: [400, 800, 1200], lqip: 'data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAwBACdASoUABQAPu1qq08ppiOiMBgIATAdiWQAsRtcgKlj+GHMcLdr3AAA/vOCgChQ5B2OyCwG58UgM/go28ODT24NG7j2MdSFo6RQ/UFnNyeLxPVFu906vgAAAA==' },
  'semo': { widths: [400, 800, 1200], lqip: 'data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAACwBACdASoUABQAPu1gqU2ppaOiMBgMATAdiWIAxNgNcK/ZGjWV42QvacejIw4AAP7x4Ee7ZwiRh+gE+uxWTd84vb5iqwwB9hhFBUSTQFQYjbh4AAA=' },
  'sossa': { widths: [400, 800, 1200], lqip: 'data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAADwBACdASoUABQAPu1cqE2ppKOiN/VYATAdiWIAxNgR9StfXicK5TEc0E3z0vZq0ogA/uGHD7SUj9IHwjvc88rRH1SiuTOljbi5274xGR86hqf1KNeeNxslI9OAlQ5MvBE/mGAA' },
  'spicy-rice': { widths: [400, 800, 1200], lqip: 'data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAABwBQCdASoUABQAPulep02pJSOiN/VYASAdCWwAnTMcYA4gQFK24zHip/C1f/trWnYRVJwAAP7x35iqq4x3LVLXxg4ZvE3IdrZeMuf3LNJZgUjGd2eC4PNV1ktTEuZ2HQXBZwMvDnTmo/+mvHEhrkex0l0BmZeadfMSoRTiAAA=' },
  'sprite': { widths: [400, 800, 1200], lqip: 'data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAAAQBACdASoUABQAPu1uq1EppiOiqAqpMB2JZwAALa5hO/2bYuz3STw0AAD+834JR2TTeIR/l+x2G3DEWutzfhBJZQBAAA==' },
  'titus': { widths: [400, 800, 1200], lqip: 'data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAADwBACdASoUABQAPu1mq08ppaOiKA1RMB2JbACdL3cT+gOMKYVLSMlI2SKPS/sf5oAA/vBB623Khjjt1DIoQnj0ACuelhgkmY4GRpEaPBPc2bqZrnO/y5Akq7p7RL3RWcZMbdBrSm66zXuvONiX1p6GkIl9z3ag9QdRq0CoUUDoNgkZzQAAAA==' },
  'turkey': { widths: [400, 800, 1200], lqip: 'data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAABQBQCdASoUABQAPu1krE4ppaSiKA1RMB2JbACdMoPHDBTufQOt1gLxiXXCbo5WkrPU5oAA/u4081JbxutQGB839DKEL3imtna2vkq7qPhj3BhOpoa4vGI7ednm3hp4sCeySEyxtHfVB5z9RxTrYKT/x9OmbQX5W+9TMMdwrGJHHaAA' },
  'yam-porridge': { widths: [400, 800, 1200], lqip: 'data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAABwBQCdASoUABQAPu1oq08ppiOiKA1RMB2JbACdMoR5mIK4t3GgDBxV3HdZHRS8tddCT/EgAP4BbCYughuBJwcx2gLzx9G5E6uyieD0Qjx68yrkVbtKXTa/3iqJ+M57YISYmUzndpoyXWJRtUqiUlpT3LjFNYJ6oW+Wm6GNIobhjdFxv+D4kJx5tDmgAA==' },
  'yogurt': { widths: [400, 800, 1200], lqip: 'data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAABwBACdASoUABQAPu1eqk2ppKQjMBgMATAdiWUAv+wMLtc1xAQe2SfhxpOFQAD+79c1Eq1NycyFti3z0+8hnK3dUUCPG6FUz4OdloA7g58cpD8H3K8DogAA' },
};

export const hasPhoto = (slug: string): boolean => slug in PHOTOS;
